export { default as Appointment } from "./Appointment";
export { default as Blog } from "./Blog";
export { default as Folds } from "./Folds";
export { default as Header } from "./Header";
export { default as Hero } from "./Hero";
export { default as Footer } from "./Footer";
export { default as Gallery } from "./Gallery";
export { default as SocialLink } from "./SocialLink";
export { default as Logo } from "./Logo";
export { default as Loader } from "./Loader";
export { default as ScrollTop } from "./ScrollTop";
export { default as ShortFooter } from "./ShortFooter";
export { default as SignIn } from "./SignIn";
export { default as SignUp } from "./SignUp";
export { default as Slide } from "./Slide";
export { default as Testimony } from "./Testimony";
export { default as Tutors } from "./Tutors";
export { default as NewsLetter } from "./NewsLetter";

